#!/usr/bin/env python3
"""Cross-platform installer for workflow-checkpoint SessionStart hook.

    python install.py             # install
    python install.py --dry-run   # preview only
"""

import json
import stat
import sys
from pathlib import Path

HOME = Path.home()
CLAUDE_DIR = HOME / ".claude"
SKILL_DIR = HOME / ".claude" / "skills" / "workflow-checkpoint"
HOOK_DIR = SKILL_DIR / "hooks"
TASK_CLI = SKILL_DIR / "scripts" / "task-cli.py"
SETTINGS = CLAUDE_DIR / "settings.json"
PYTHON = sys.executable  # the Python running right now — zero search needed


_HOOK_PS1 = """\
# SessionStart hook: pending-task reminder.
# Auto-generated by workflow-checkpoint install.py. Do not edit manually.

$ErrorActionPreference = "Stop"
$json = & "__PYTHON__" "__TASK_CLI__" list --json 2>$null
if (-not $json) { exit 0 }
try { $tasks = $json | ConvertFrom-Json } catch { exit 0 }
$pending = $tasks | Where-Object { $_.event -eq "active" -or $_.event -eq "paused" }
if (-not $pending -or $pending.Count -eq 0) { exit 0 }
$count = $pending.Count
$slugs = ($pending | ForEach-Object { $_.slug }) -join ", "
$ctx = "You have $count pending task(s): $slugs. Tell the user what's pending and ask if they want to resume any."
$escaped = $ctx -replace '\\\\', '\\\\' -replace '"', '\\"'
Write-Output "{""hookSpecificOutput"":{""hookEventName"":""SessionStart"",""additionalContext"":""$escaped""}}"
exit 0
"""

_HOOK_SH = """\
#!/usr/bin/env bash
# SessionStart hook: pending-task reminder.
# Auto-generated by workflow-checkpoint install.py. Do not edit manually.
set -e
json="$(__PYTHON__ __TASK_CLI__ list --json 2>/dev/null)"
[ -z "$json" ] && exit 0
count=$(echo "$json" | __PYTHON__ -c "import sys,json; d=json.load(sys.stdin); print(len([t for t in d if t.get('event') in ('active','paused')]))" 2>/dev/null)
[ "$count" = "0" ] && exit 0
slugs=$(echo "$json" | __PYTHON__ -c "import sys,json; d=json.load(sys.stdin); print(', '.join([t['slug'] for t in d if t.get('event') in ('active','paused')]))" 2>/dev/null)
echo '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"You have '$count' pending task(s): '$slugs'. Tell the user what's pending and ask if they want to resume any."}}'
exit 0
"""

_HOOK_JSON = {
    "type": "command",
    "async": False,
    "command": None,  # filled at install time
}


def main():
    dry_run = "--dry-run" in sys.argv
    is_win = sys.platform == "win32"

    hook_name = "check-pending-tasks.ps1" if is_win else "check-pending-tasks.sh"
    hook_path = HOOK_DIR / hook_name
    template = _HOOK_PS1 if is_win else _HOOK_SH
    hook_content = template.replace("__PYTHON__", PYTHON).replace("__TASK_CLI__", str(TASK_CLI))

    # Resolve existing settings.json
    if not SETTINGS.exists():
        print(f"settings.json not found at {SETTINGS}. Run Claude Code once first.")
        sys.exit(1)
    cfg = json.loads(SETTINGS.read_text(encoding="utf-8"))

    # Build hook command for settings.json
    if is_win:
        cmd = f'powershell -NoProfile -ExecutionPolicy Bypass -Command "[Console]::OutputEncoding=[Text.Encoding]::UTF8; & \'{hook_path}\'"'
    else:
        cmd = f'bash "{hook_path}"'

    hook_json = {**_HOOK_JSON, "command": cmd}

    # Dry-run: show what would happen
    if dry_run:
        print(f"Platform:    {'Windows' if is_win else 'Linux/macOS'}")
        print(f"Python:      {PYTHON}")
        print(f"Hook script: {hook_path}")
        print(f"Hook cmd:    {cmd}")
        print(f"Settings:    {SETTINGS}")
        print()
        print("[DRY-RUN] Run without --dry-run to install.")
        return

    # Write hook script
    HOOK_DIR.mkdir(parents=True, exist_ok=True)
    hook_path.write_text(hook_content, encoding="utf-8")
    if not is_win:
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Register in settings.json
    session_hooks = cfg.setdefault("hooks", {}).setdefault("SessionStart", [])
    if session_hooks:
        entry = session_hooks[0]
        hooks_list = entry.setdefault("hooks", [])
        existing = [h for h in hooks_list if "workflow-checkpoint" in h.get("command", "")]
        if existing:
            hooks_list.remove(existing[0])
        hooks_list.append(hook_json)
    else:
        session_hooks.append({
            "matcher": "startup|clear|compact",
            "hooks": [hook_json],
        })

    SETTINGS.write_text(json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8")

    # Update CLAUDE.md — add Workflow section if not present
    claude_md = CLAUDE_DIR / "CLAUDE.md"
    if claude_md.exists():
        content = claude_md.read_text(encoding="utf-8")
        if "workflow-checkpoint" not in content:
            new_section = (
                "\n## Workflow\n"
                "- Use `workflow-checkpoint` skill for task tracking, pause, resume, and completion\n"
                "- Skill path: `~/.claude/skills/workflow-checkpoint/`\n"
            )
            # Insert after Language section, before Memory System or at end
            if "## Memory System" in content:
                content = content.replace("## Memory System", new_section + "\n## Memory System")
            elif "## Language" in content:
                idx = content.index("## Language")
                # Find end of Language section (next ## or <!--)
                rest = content[idx:]
                import re
                m = re.search(r"\n(?=## |<!--)", rest[12:])
                if m:
                    insert_at = idx + 12 + m.start()
                    content = content[:insert_at] + "\n" + new_section + content[insert_at:]
                else:
                    content += "\n" + new_section
            else:
                content += "\n" + new_section
            claude_md.write_text(content, encoding="utf-8")
            print(f"  CLAUDE.md: added workflow-checkpoint reference")
        else:
            print(f"  CLAUDE.md: workflow-checkpoint already referenced")
    else:
        print(f"  CLAUDE.md not found — create it and reference workflow-checkpoint manually")

    print("Installed.")
    print(f"  Hook: {hook_path}")
    print(f"  Settings: {SETTINGS}")


if __name__ == "__main__":
    main()
